name: course_management_system
description: A comprehensive course management system built with Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  video_player: ^2.10.0
  shared_preferences: ^2.1.1
  youtube_player_iframe: ^4.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/images/withname png.png
    - lib/images/avatar.jpg
    - lib/images/gannetz.mp4
    - lib/images/gannetz1.mp4